// Note: this file is generated by `script/generate-regex.js`
export const abbreviations =
  /^(t(?:hurs|bsp|sp)|s(?:e(?:pt|c)|q)|(?:tue|bbl|yd)s|thu|sep|tue|bbl|nov|aug|ju[ln]|(?:ap|h)r|(?:ja|su)n|m(?:ar|on|in)|(?:sa|oc|[kpq])t|g(?:ro|al)|f(?:eb|ri|[lt])|d(?:ec|oz)|wed|l(?:bs|td)|inc?|mi|gr|yd|lb|oz|cu)$/

export const abbreviationsSensitive =
  /^((?:Northant|Derby|S(?:hrop|taff)|W(?:ark|orc)|L(?:in|ei|an)c|C(?:amb|he)|Trea|York|B(?:uck|e(?:rk|d))|(?:Not|Wil)t|H(?:er|[au]n)t|Glo|Pre)s|Northumb|N(?:or(?:thd|f)|e(?:br|v)|atl)|M(?:(?:essr|as|se)s|i(?:ddx|nn|ch|ss)|ont|lle|s(?:gr|s)|ddx|(?:me|r)s?|a[jn]|ex|gr|o|d|e|s|[tx])?|Heref|P(?:enna|[ahot])|D(?:e(?:rbs|[lv])|r)|Westm|(?:Cali|Pro)f|S(?:a(?:lop|sk)|uff|om|e[cn]|[qrxy])|(?:Bldg|Kan)s?|Here|P(?:enn?|k)|St(?:af)?|W(?:isc|arw|yo)|C(?:umb|olo)|B(?:lvd|rig)|(?:Ok|F)la|(?:Pk|[FH])wy|A(?:r(?:iz|k)|lt?a|tty|m[bd])|(?:Cap|S(?:up|g)|On|Ru|U)t|(?:Ter|Cd|D[ou]|Sn|J)r|(?:Oxo|Co[nr]|Ten|Ke|Ge|Ho)n|Wash|N(?:eb|at)|W(?:is|ar|o)|C(?:al|ol?)|Qu[e\u00E9]|I(?:ll|a)|Tex|G(?:ov|a)|Ind|R(?:te|e[pv]|d)|Ida|(?:Yu|Da)k|(?:Or|Av)e|Ssx|Ok|La|Br|Rt|Id|V[at]|Ky|Lt|F[rt])$/

export const elisionPrefix = /^(ol?)$/

export const elisionAffix = /^(t(?:were|(?:wa|i)s)|cause|e[mr]|im|\d\ds?)$/
